# Generated by Django 5.2.7 on 2025-12-18 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_contactmessage_options_alter_project_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('web', 'Web Design'), ('php', 'PHP Projects'), ('python', 'Python Projects'), ('mobile', 'Mobile App')], default='web', max_length=20, verbose_name='အမျိုးအစား'),
        ),
    ]
