# Generated by Django 5.2.7 on 2025-12-22 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_project_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='vercel_link',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Vercel လင့်ခ်'),
        ),
    ]
